[[repos]]
repo = "builtin"
hooks = [
  {id = "check-merge-conflict"},
  {id = "check-toml"},
  {id = "check-yaml"},
  {id = "end-of-file-fixer"},
  {id = "trailing-whitespace"}
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.2"
hooks = [
  {id = "ruff-check", args = ["--fix", "--show-fixes"]},
  {id = "ruff-format"}
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.43.5"
hooks = [{id = "typos"}]
